[project]
name = "scallop-transformers"
version = "0.0.1"
dependencies = [
  "transformers",
  "opencv-python",
  "torch",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."scallop.plugin.load_into_context"]
transformers = "scallop_transformers:load_into_context"
