[project]
name = "scallop-face-detection"
version = "0.0.1"
dependencies = [
  "face_detection",
  "torch",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."scallop.plugin.load_into_context"]
face-detection = "scallop_face_detection:load_into_context"
